version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: infrastructure/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/views.json:/app/views.json
    restart: always
